"""
Unit tests for src/build_library.py — the refactor that turned the 14
confirmed report shapes into pure, side-effect-free enquiry_NN_*()
functions (a single source of truth both main() and src/templates.py call).

The refactor's actual behavior-preservation was verified once, by hand,
comparing a full regenerated generated/ tree against a pre-refactor
snapshot byte-for-byte (modulo the exportDate timestamp) — these tests
guard the properties that matter going forward: importing the module never
writes anything, every enquiry_NN_*() function returns a well-formed spec
dict, build_export() produces output that validates clean, and every spec
in ENQUIRIES/generated by main() ends up in generated/ under the module
folder CLAUDE.md expects.
"""
import glob
import importlib
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import build_library as lib
from enquiry_validator import validate_file

REQUIRED_SPEC_KEYS = {"filename", "description", "group", "params", "selects",
                       "propmeta", "layouts", "permissions", "notes"}

KNOWN_MODULE_FOLDERS = {"gl", "ar", "ap", "sales", "purchasing", "bank", "budgets"}


def _validate_env(env):
    fd, path = tempfile.mkstemp(suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(env)
        return validate_file(path)
    finally:
        os.unlink(path)


class TestImportHasNoSideEffects(unittest.TestCase):
    def test_reimporting_does_not_touch_generated_dir(self):
        generated_dir = os.path.join(os.path.dirname(lib.__file__), "..", "generated")
        before = {}
        for path in glob.glob(os.path.join(generated_dir, "*", "*.json")):
            before[path] = os.path.getmtime(path)

        importlib.reload(lib)

        after = {}
        for path in glob.glob(os.path.join(generated_dir, "*", "*.json")):
            after[path] = os.path.getmtime(path)
        self.assertEqual(before, after,
                          "importing/reloading build_library.py must never write to generated/")


class TestEnquiryFunctionsReturnWellFormedSpecs(unittest.TestCase):
    def test_all_14_enquiries_registered(self):
        self.assertEqual(len(lib.ENQUIRIES), 14)

    def test_every_spec_has_required_keys(self):
        for make in lib.ENQUIRIES:
            spec = make()
            missing = REQUIRED_SPEC_KEYS - set(spec.keys())
            self.assertFalse(missing, f"{make.__name__}() spec missing keys: {missing}")

    def test_every_filename_is_under_a_known_module_folder(self):
        for make in lib.ENQUIRIES:
            spec = make()
            folder = spec["filename"].split("/")[0]
            self.assertIn(folder, KNOWN_MODULE_FOLDERS,
                          f"{make.__name__}()'s filename {spec['filename']!r} isn't under a "
                          "module folder CLAUDE.md recognizes")

    def test_filenames_are_unique(self):
        filenames = [make()["filename"] for make in lib.ENQUIRIES]
        self.assertEqual(len(filenames), len(set(filenames)))

    def test_calling_a_function_twice_returns_independent_specs(self):
        # Each enquiry_NN_*() function must build its own params/selects
        # fresh, not hand back a shared mutable dict/list a caller (e.g.
        # templates.py building the same report twice) could corrupt for
        # the next caller.
        spec_a = lib.enquiry_01_gl_trial_balance()
        spec_b = lib.enquiry_01_gl_trial_balance()
        self.assertIsNot(spec_a["params"], spec_b["params"])
        self.assertIsNot(spec_a["selects"], spec_b["selects"])


class TestBuildExportValidatesClean(unittest.TestCase):
    def test_every_enquiry_builds_and_validates_clean(self):
        for make in lib.ENQUIRIES:
            spec = make()
            env, model = lib.build_export(spec)
            issues = _validate_env(env)
            self.assertEqual(issues, [], f"{make.__name__}() failed validation: {issues}")

    def test_description_override_is_applied(self):
        spec = lib.enquiry_01_gl_trial_balance()
        env, model = lib.build_export(spec, description="A customer's own wording")
        self.assertEqual(model["Description"], "A customer's own wording")
        # Overriding the description must not touch the underlying report
        # shape (same rows/columns) — only the label on the export.
        self.assertEqual(model["Group"], spec["group"])

    def test_no_description_override_falls_back_to_spec(self):
        spec = lib.enquiry_04_pl_by_month()
        env, model = lib.build_export(spec)
        self.assertEqual(model["Description"], spec["description"])


class TestEmitAndMain(unittest.TestCase):
    def test_emit_writes_expected_file_and_matches_build_export(self):
        spec = lib.enquiry_02_gl_detail_by_nominal()
        env, _ = lib.build_export(spec)
        with tempfile.TemporaryDirectory() as tmp:
            old_generated = lib.GENERATED
            lib.GENERATED = tmp
            try:
                path = lib.emit(spec)
                self.assertTrue(os.path.isfile(path))
                with open(path, encoding="utf-8") as f:
                    written = f.read()
                # exportDate differs (wall-clock), so compare everything else.
                self.assertEqual(
                    written.split('"exportDate"')[0], env.split('"exportDate"')[0])
            finally:
                lib.GENERATED = old_generated

    def test_main_writes_all_14_plus_catalog(self):
        with tempfile.TemporaryDirectory() as tmp:
            old_generated = lib.GENERATED
            lib.GENERATED = tmp
            try:
                lib.main()
                written = glob.glob(os.path.join(tmp, "*", "*.json"))
                self.assertEqual(len(written), 14)
                self.assertTrue(os.path.isfile(os.path.join(tmp, "catalog.json")))
            finally:
                lib.GENERATED = old_generated


if __name__ == "__main__":
    unittest.main()
